apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data
  namespace: mcp-soccer-news
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ocs-storagecluster-ceph-rbd
  resources:
    requests:
      storage: 20Gi
